INSERT INTO administrador (nome_adm,email_adm,cpf_adm,senha_adm,telefone_adm) 
VALUES ("adminSA", "admin.gestor@hotmail.com","57660489046","masteradmin","21973595673");


INSERT INTO `evento` (`cod_evento`, `nome_evento`, `data_evento`, `hora_evento`, `imagem_evento`, `desc_evento`, `cep_evento`, `estado_evento`, `cidade_evento`, `bairro_evento`, `rua_evento`, `complemento_evento`) VALUES
(1, 'Vamos saborear alguns pastéis?', '2019-08-09', '10:45:00', 'eventopastel.jpg', 'Com o sucesso dos nossos festivais de pastel e pizza, por que não repetir a dose de novo? Mais uma vez\n                a SIBPP está realizando o famoso Festival de Pastel!! É a partir das 17h, hein? Não percam!', '24412040', 'RJ', 'São Gonçalo', 'Sete Pontes', 'teste teste teste 309', 'casa'),
(2, 'Vamos curtir o nosso arraiá na presença do Senhor!', '2019-08-09', '10:20:00', 'eventofesta.jpg', 'Já estamos no mês de Junho e todos pensam na Festa Junina!! E a nossa igreja não ficará de fora! Amanhã\r\nteremos a nossa Festa da Roça!!! Tragam seus entes queridos, amigos para pular a fogueira e comer milho!', '24412040', 'RJ', 'São Gonçalo', 'Sete Pontes', 'teste teste teste 309', 'casa'),
(3, 'Vamos tirar um tempinho para Deus?', '2019-08-09', '18:15:00', 'eventoluau.jpg', 'Um dia tranquilo com louvores e bate papo com Deus, vamos aproveitar o nosso pequeno Lual para ficar mais próximo do nosso salvador!', '24412040', 'RJ', 'São Gonçalo', 'Sete Pontes', 'teste teste teste 309', 'casass'),
(4, 'Venha participar de um rodízio com Deus.', '2019-08-09', '19:10:00', 'eventopizza.jpg', 'O sucesso foi grande com os pastéis e recebemos muitas recomendações pra fazer de pizza!! Oramos e Deus nos permitiu para realizar este evento!! Tragam a família, amigos e conhecidos para aproveitar o nosso festival de pizza!', '24412040', 'RJ', 'São Gonçalo', 'Sete Pontes', '1212olavo lamego', 'teste12'),
(5, 'Mais um festival de pastéis, topam?', '2019-08-09', '19:12:00', 'eventopastel2.jpeg', 'Estamos realizando um evento onde podem levar a família para comer pastéis e tomar caldo de cana!\r\n                Gostoso, né? Leva a criançada, os amigos e vamos aproveitar!!!', '24412040', 'AL', 'São Gonçalo', 'Sete Pontes', '1212olavo lamego', 'casass'),
(6, ' Traga um amigo para conhecer o Salvador.', '2019-08-09', '19:14:00', 'eventoamigo.jpg', 'Tem um amigo afastado da igreja? Ou um amigo que não conhece a Deus? Que tal trazê-lo e fazer com que o\r\n                Espírito Santo o mostre quem foi que o salvou de todos os pecados?! Neste culto está destinado aos\r\n                amigos, tragam-nos para conhecer a casa do nosso Pai Celestial.', '24412040', 'RJ', 'São Gonçalo', 'Sete Pontes', 'teste teste teste 309', 'teste12');
